name: yubikiri
description: "An architecture package that simplifies state management by adding an easy MVVM solution based on ValueNotifiers"
topics:
  - architecture
  - state-management
  - mvvm
  - yubikiri
repository: https://github.com/sillydomnom/yubikiri

version: 0.1.0

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  mocktail: ^1.0.4
  meta: ^1.16.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

